// OpenTelemetry instrumentation for Go-rest-api — generated by TelemetryOS.
// SLO contract v1. SLIs covered: Go-rest-api — HTTP Worker Pool Saturation.
// Adapt the snippets below to your service; they are grounded scaffolds.

package telemetry

import "go.opentelemetry.io/otel"

var (
	meter  = otel.Meter("Go-rest-api")
	tracer = otel.Tracer("Go-rest-api")
)

// ── SLI: Go-rest-api — HTTP Worker Pool Saturation (go-rest-api-http-saturation) — complexity: medium ──
// Active-request and pool-size gauges
activeRequests, _ := meter.Int64ObservableGauge("http.server.active_requests")
poolSize, _ := meter.Int64ObservableGauge("http.server.worker_pool.size")

meter.RegisterCallback(func(_ context.Context, o metric.Observer) error {
  o.ObserveInt64(activeRequests, server.ActiveRequests())
  o.ObserveInt64(poolSize, int64(server.MaxWorkers()))
  return nil
}, activeRequests, poolSize)
