# OpenTelemetry instrumentation for Go-rest-api — generated by TelemetryOS.
# SLO contract v1. SLIs covered: Go-rest-api — HTTP 5xx Error Rate, Primary Flow — Flow Completion Freshness.
# Adapt the snippets below to your service; they are grounded scaffolds.

from opentelemetry import metrics, trace

meter = metrics.get_meter("Go-rest-api")
tracer = trace.get_tracer("Go-rest-api")

# ── SLI: Go-rest-api — HTTP 5xx Error Rate (go-rest-api-http-error-rate) — complexity: low ──
# Exception-to-status mapping span attribute
from opentelemetry import trace

@app.exception_handler(Exception)
async def handle_exception(request, exc):
    span = trace.get_current_span()
    span.set_attribute("error.type", type(exc).__name__)
    span.set_status(trace.StatusCode.ERROR, str(exc))
    return JSONResponse(status_code=500, content={"error": "internal_error"})

# ── SLI: Primary Flow — Flow Completion Freshness (flow-primary-flow-e2e-flow-freshness) — complexity: high ──
# Entry-to-terminal duration histogram
entry_to_terminal = meter.create_histogram("flow.entry_to_terminal.duration", unit="s")

# on terminal state transition
elapsed = (now() - entry_timestamp).total_seconds()
entry_to_terminal.record(elapsed, {"flow": "order_entry", "terminal_state": new_state})
