// OpenTelemetry instrumentation for Go-rest-api — generated by TelemetryOS.
// SLO contract v1. SLIs covered: Go-rest-api — HTTP Response Time P99, Go-rest-api — Authentication Failure Rate.
// Adapt the snippets below to your service; they are grounded scaffolds.

import io.opentelemetry.api.GlobalOpenTelemetry;
import io.opentelemetry.api.metrics.Meter;
import io.opentelemetry.api.trace.Tracer;

// Integrate the snippets below into your service. This file is a
// scaffold, not a drop-in compilable unit.
// Meter meter = GlobalOpenTelemetry.getMeter("Go-rest-api");
// Tracer tracer = GlobalOpenTelemetry.getTracer("Go-rest-api");

// ── SLI: Go-rest-api — HTTP Response Time P99 (go-rest-api-http-latency-p99) — complexity: medium ──
// Slow-request span events
long start = System.nanoTime();
try {
  return handler.handle(request);
} finally {
  long elapsedMs = (System.nanoTime() - start) / 1_000_000;
  if (elapsedMs > 750) {
    Span.current().addEvent("slow_request",
      Attributes.of(AttributeKey.longKey("duration_ms"), elapsedMs));
  }
}

// ── SLI: Go-rest-api — Authentication Failure Rate (go-rest-api-http-auth-failure-rate) — complexity: low ──
// Auth attempt outcome counter
LongCounter authAttempts = meter.counterBuilder("auth.attempts")
  .setDescription("Authentication/authorization decisions")
  .build();

authAttempts.add(1, Attributes.of(
  AttributeKey.stringKey("outcome"), result.isAllowed() ? "allowed" : "denied",
  AttributeKey.stringKey("reason"), result.getReasonCode()
));
