// OpenTelemetry instrumentation for Go-rest-api — generated by TelemetryOS.
// SLO contract v1. SLIs covered: Go-rest-api — HTTP Response Time P99, Go-rest-api — Authentication Failure Rate, Primary Flow — E2E Business Flow Success Rate, Primary Flow — E2E Business Flow Latency P95, Primary Flow — Flow Validation Failure Rate.
// Adapt the snippets below to your service; they are grounded scaffolds.

import io.opentelemetry.api.GlobalOpenTelemetry;
import io.opentelemetry.api.metrics.Meter;
import io.opentelemetry.api.trace.Tracer;

// Integrate the snippets below into your service. This file is a
// scaffold, not a drop-in compilable unit.
// Meter meter = GlobalOpenTelemetry.getMeter("Go-rest-api");
// Tracer tracer = GlobalOpenTelemetry.getTracer("Go-rest-api");

// ── SLI: Go-rest-api — HTTP Response Time P99 (go-rest-api-http-latency-p99) — complexity: medium ──
// Slow-request span events
long start = System.nanoTime();
try {
  return handler.handle(request);
} finally {
  long elapsedMs = (System.nanoTime() - start) / 1_000_000;
  if (elapsedMs > 750) {
    Span.current().addEvent("slow_request",
      Attributes.of(AttributeKey.longKey("duration_ms"), elapsedMs));
  }
}

// ── SLI: Go-rest-api — Authentication Failure Rate (go-rest-api-http-auth-failure-rate) — complexity: low ──
// Auth attempt outcome counter
LongCounter authAttempts = meter.counterBuilder("auth.attempts")
  .setDescription("Authentication/authorization decisions")
  .build();

authAttempts.add(1, Attributes.of(
  AttributeKey.stringKey("outcome"), result.isAllowed() ? "allowed" : "denied",
  AttributeKey.stringKey("reason"), result.getReasonCode()
));

// ── SLI: Primary Flow — E2E Business Flow Success Rate (flow-primary-flow-e2e-flow-success) — complexity: medium ──
// Flow outcome span and counter
Span flowSpan = tracer.spanBuilder("flow.order_entry").startSpan();
try (Scope scope = flowSpan.makeCurrent()) {
  boolean ok = runFlow(orderId);
  flowOutcomes.add(1, Attributes.of(
    AttributeKey.stringKey("flow"), "order_entry",
    AttributeKey.stringKey("outcome"), ok ? "success" : "failure"
  ));
} finally {
  flowSpan.end();
}

// ── SLI: Primary Flow — E2E Business Flow Latency P95 (flow-primary-flow-e2e-flow-latency) — complexity: medium ──
// End-to-end correlation key
ProducerRecord<String, byte[]> record = new ProducerRecord<>(topic, key, value);
record.headers().add("traceparent",
  W3CTraceContextPropagator.getInstance()
    .extract(Context.current(), record, KAFKA_GETTER)
    .toString().getBytes(StandardCharsets.UTF_8));
producer.send(record);

// ── SLI: Primary Flow — Flow Validation Failure Rate (flow-primary-flow-e2e-validation-failure-rate) — complexity: medium ──
// Per-step validation span and outcome attribute
Span stepSpan = tracer.spanBuilder("flow.validation.step")
  .setAttribute("validation.step", stepName)
  .setAttribute("flow.id", flowId)
  .startSpan();
try (Scope scope = stepSpan.makeCurrent()) {
  boolean passed = validator.validate(payload);
  stepSpan.setAttribute("validation.passed", passed);
  validationOutcomes.add(1, Attributes.of(
    AttributeKey.stringKey("step"), stepName,
    AttributeKey.stringKey("outcome"), passed ? "passed" : "failed"
  ));
} finally {
  stepSpan.end();
}
