// OpenTelemetry instrumentation for Go-rest-api — generated by TelemetryOS.
// SLO contract v1. SLIs covered: Go-rest-api — HTTP Service Availability, Go-rest-api — HTTP Response Time P95, Go-rest-api — HTTP Request Throughput, Primary Flow — E2E Business Flow Throughput.
// Adapt the snippets below to your service; they are grounded scaffolds.

import { metrics, trace } from "@opentelemetry/api";

const meter = metrics.getMeter("Go-rest-api");
const tracer = trace.getTracer("Go-rest-api");

// ── SLI: Go-rest-api — HTTP Service Availability (go-rest-api-http-availability) — complexity: low ──
// Request outcome counter
const requestOutcomes = meter.createCounter("http.server.request.outcomes", {
  description: "HTTP requests by route and outcome class",
});

app.use((req, res, next) => {
  res.on("finish", () => {
    requestOutcomes.add(1, {
      route: req.route?.path ?? "unknown",
      outcome: res.statusCode < 500 ? "success" : "failure",
    });
  });
  next();
});

// ── SLI: Go-rest-api — HTTP Response Time P95 (go-rest-api-http-latency-p95) — complexity: low ──
// Route-level latency histogram with business dimension
const requestDuration = meter.createHistogram("http.server.request.duration.business", {
  unit: "ms",
});

app.use((req, res, next) => {
  const start = performance.now();
  res.on("finish", () => {
    requestDuration.record(performance.now() - start, {
      route: req.route?.path ?? "unknown",
      tier: req.headers["x-tenant-tier"] ?? "standard",
    });
  });
  next();
});

// ── SLI: Go-rest-api — HTTP Request Throughput (go-rest-api-http-request-rate) — complexity: low ──
// Per-tenant request-rate counter
const requestsByTenant = meter.createCounter("http.server.requests.by_tenant");

app.use((req, res, next) => {
  requestsByTenant.add(1, { tenant: req.headers["x-tenant-id"] ?? "unknown" });
  next();
});

// ── SLI: Primary Flow — E2E Business Flow Throughput (flow-primary-flow-e2e-flow-throughput) — complexity: low ──
// Flow-entry counter
const flowEntries = meter.createCounter("flow.entries");

app.post("/orders", (req, res) => {
  flowEntries.add(1, { flow: "order_entry" });
  // ... existing handler
});
